apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-manb-ms
  description: FastAPI backend microservice used as a testbed for noskoski-portal (Backstage) integrations
  annotations:
    github.com/project-slug: mnoskoski/app-manb-ms
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: app-manb-ms
    backstage.io/kubernetes-namespace: default
  tags:
    - python
    - fastapi
    - microservice
spec:
  type: service
  lifecycle: experimental
  owner: group:default/guests
